### ISSUE TITLE
Do not work on sites under root directory

### ISSUE THREAD

**Issue by dpardons** [TLWebdesign/Pretty-Masthead#1]
Hi
Does not work for web sites under the root directory.
1) Does not display logo on admin page (use .. as relative path to solve the problem)
2) Incorrect url generated
ex: url("http://localhost/joomla4/index.php/extensions-j4/images/big/banner-bg.jpg") in place of http://localhost/joomla4/images/big/banner-bg.jpg

Regards
Daniel

**Comment by TLWebdesign** [comment]
I'll continue the conversation here. Yes i know what i need to do. Ad URI:base(); to the template. That will make it a full link instead of a relative. The thing joomla does with the path is not the issue and thats actually behaviour i want and use. I get the width and dimension from there using htmlhelper and calculate the image ratio to display the image correctly and responsive on screen.

**Comment by TLWebdesign** [comment]
I just uploaded a fix for this. Will generate a new release now.
